export const HOST = 'http://api.wangdian.cn/openapi2';

export const SANDBOX_HOST = 'http://sandbox.wangdian.cn/openapi2';

export const QIMEN_HOST = 'http://hu3cgwt0tc.api.taobao.com/router/qmtest';

export const QIMEN_SANDBOX_HOST = 'http://hu3cgwt0tc.api.taobao.com/router/qm';

export const PATH = {
    SHOP: { path: '/shop.php', qimenMethod: 'wdt.shop.query' },
    WAREHOUSE_QUERY: { path: '/warehouse_query.php', qimenMethod: 'wdt.warehouse.query' },
    LOGISTICS: { path: '/logistics.php', qimenMethod: 'wdt.logistics.query' },
    PURCHASE_PROVIDER_QUERY: { path: '/purchase_provider_query.php', qimenMethod: 'wdt.purchase.provider.query' },
    PURCHASE_PROVIDER_CREATE: { path: '/purchase_provider_create.php', qimenMethod: 'wdt.purchase.provider.create' },
    GOODS_PUSH: { path: '/goods_push.php', qimenMethod: 'wdt.goods.push' },
    GOODS_QUERY: { path: '/goods_query.php', qimenMethod: 'wdt.goods.query' },
    API_GOODSSPEC_PUSH: { path: '/api_goodsspec_push.php', qimenMethod: 'wdt.api.goodsspec.push' },
    VIP_API_GOODS_QUERY: { path: '/vip_api_goods_query.php', qimenMethod: 'wdt.vip.api.goods.query' },
    SUITES_QUERY: { path: '/suites_query.php', qimenMethod: 'wdt.suites.query' },
    GOODS_CLASS_QUERY: { path: '/goods_class_query.php', qimenMethod: 'wdt.goods.class.query' },
    TRADE_PUSH: { path: '/trade_push.php', qimenMethod: 'wdt.trade.push' },
    TRADE_QUERY: { path: '/trade_query.php', qimenMethod: 'wdt.trade.query' },
    STOCKOUT_ORDER_QUERY_TRADE: { path: '/stockout_order_query_trade.php', qimenMethod: 'wdt.stockout.order.query.trade' },
    LOGISTICS_SYNC_QUERY: { path: '/logistics_sync_query.php', qimenMethod: 'wdt.logistics.sync.query' },
    LOGISTICS_SYNC_ACK: { path: '/logistics_sync_ack.php', qimenMethod: 'wdt.logistics.sync.ack' },
    API_GOODS_STOCK_CHANGE_QUERY: { path: '/api_goods_stock_change_query.php', qimenMethod: 'wdt.api.goods.stock.change.query' },
    API_GOODS_STOCK_CHANGE_ACK: { path: '/api_goods_stock_change_ack.php', qimenMethod: 'wdt.api.goods.stock.change.ack' },
    VIP_STAT_SALES_BY_SPEC_SHOP_WAREHOUSE_QUERY: { path: '/vip_stat_sales_by_spec_shop_warehouse_query.php', qimenMethod: 'wdt.vip.stat.sales.by.spec.shop.warehouse.query' },
    VIP_STOCKOUT_SALES_WEIGHT_PUSH: { path: '/vip_stockout_sales_weight_push.php', qimenMethod: 'wdt.vip.stockout.sales.weight.push' },
    VIP_TRADE_MODIFY: { path: '/vip_trade_modify.php', qimenMethod: 'wdt.vip.trade.modify' },
    VIP_API_TRADE_QUERY: { path: '/vip_api_trade_query.php', qimenMethod: 'wdt.vip.api.trade.query' },
    VIP_INVOICE_INFO_QUERY: { path: '/vip_invoice_info_query.php', qimenMethod: 'wdt.vip.invoice.info.query' },
    VIP_INVOICE_INFO_UPDATE: { path: '/vip_invoice_info_update.php', qimenMethod: 'wdt.vip.invoice.info.update' },
    SALES_REFUND_PUSH: { path: '/sales_refund_push.php', qimenMethod: 'wdt.sales.refund.push' },
    STOCKIN_REFUND_PUSH: { path: '/stockin_refund_push.php', qimenMethod: 'wdt.stockin.refund.push' },
    REFUND_QUERY: { path: '/refund_query.php', qimenMethod: 'wdt.refund.query' },
    STOCKIN_ORDER_QUERY_REFUND: { path: '/stockin_order_query_refund.php', qimenMethod: 'wdt.stockin.order.query.refund' },
    VIP_STAT_REFUND_BY_SPEC_SHOP_WAREHOUSE_QUERY: { path: '/vip_stat_refund_by_spec_shop_warehouse_query.php', qimenMethod: 'wdt.vip.stat.refund.by.spec.shop.warehouse.query' },
    VIP_API_REFUND_QUERY: { path: '/api_refund_query.php', qimenMethod: 'wdt.api.refund.query' },
    PURCHASE_ORDER_PUSH: { path: '/purchase_order_push.php', qimenMethod: 'wdt.purchase.order.push' },
    STOCKIN_PURCHASE_PUSH: { path: '/stockin_purchase_push.php', qimenMethod: 'wdt.stockin.purchase.push' },
    PURCHASE_ORDER_QUERY: { path: '/purchase_order_query.php', qimenMethod: 'wdt.purchase.order.query' },
    STOCKIN_ORDER_QUERY_PURCHASE: { path: '/stockin_order_query_purchase.php', qimenMethod: 'wdt.stockin.order.query.purchase' },
    PURCHASE_RETURN_PUSH: { path: '/purchase_return_push.php', qimenMethod: 'wdt.purchase.return.push' },
    PURCHASE_RETURN_ORDER_PUSH: { path: '/purchase_return_order_push.php', qimenMethod: 'wdt.purchase.return.order.push' },
    PURCHASE_RETURN_QUERY: { path: '/purchase_return_query.php', qimenMethod: 'wdt.purchase.return.query' },
    STOCKOUT_ORDER_QUERY_RETURN: { path: '/stockout_order_query_return.php', qimenMethod: 'wdt.stockout.order.query.return' },
    PURCHASE_APPLY_QUERY: { path: '/purchase_apply_query.php', qimenMethod: 'wdt.purchase.apply.query' },
    STOCK_QUERY: { path: '/stock_query.php', qimenMethod: 'wdt.stock.query' },
    STOCK_SYNC_BY_PD: { path: '/stock_sync_by_pd.php', qimenMethod: 'wdt.stock.sync.by.pd' },
    STOCK_PD_ORDER_QUERY: { path: '/stock_pd_order_query.php', qimenMethod: 'wdt.stock.pd.order.query' },
    STOCKIN_ORDER_PUSH: { path: '/stockin_order_push.php', qimenMethod: 'wdt.stockin.order.push' },
    STOCKIN_ORDER_QUERY: { path: '/stockin_order_query.php', qimenMethod: 'wdt.stockin.order.query' },
    STOCKOUT_ORDER_PUSH: { path: '/stockout_order_push.php', qimenMethod: 'wdt.stockout.order.push' },
    STOCKOUT_ORDER_QUERY: { path: '/stockout_order_query.php', qimenMethod: 'wdt.stockout.order.query' },
    STOCK_TRANSFER_PUSH: { path: '/stock_transfer_push.php', qimenMethod: 'wdt.stock.transfer.push' },
    STOCKOUT_TRANSFER_PUSH: { path: '/stockout_transfer_push.php', qimenMethod: 'wdt.stockout.transfer.push' },
    STOCKIN_TRANSFER_PUSH: { path: '/stockin_transfer_push.php', qimenMethod: 'wdt.stockin.transfer.push' },
    STOCK_TRANSFER_QUERY: { path: '/stock_transfer_query.php', qimenMethod: 'wdt.stock.transfer.query' },
    VIP_STOCK_QUERY_ALL: { path: '/vip_stock_query_all.php', qimenMethod: 'wdt.vip.stock.query.all' },
    VIP_WMS_STOCKINOUT_ORDER_PUSH: { path: '/vip_wms_stockinout_order_push.php', qimenMethod: 'wdt.vip.wms.stockinout.order.push' },
    VIP_STOCK_OUTSIDE_WMS_QUERY: { path: '/vip_stock_outside_wms_query.php', qimenMethod: 'wdt.vip.stock.outside.wms.query' },
    VIP_JIT_RETURN_STOCKIN_ORDER_QUERY: { path: '/vip_jit_return_stockin_order_query.php', qimenMethod: 'wdt.vip.jit.return.stockin.order.query' },
    VIP_JIT_STOCKOUT_ORDER_QUERY: { path: '/vip_jit_stockout_order_query.php', qimenMethod: 'wdt.vip.jit.stockout.order.query' },
};
