export const HOST = 'http://api.wangdian.cn/openapi2';

export const SANDBOX_HOST = 'http://sandbox.wangdian.cn/openapi2';

export const QIMEN_HOST = 'http://hu3cgwt0tc.api.taobao.com/router/qm';

export const QIMEN_SANDBOX_HOST = 'http://hu3cgwt0tc.api.taobao.com/router/qmtest';

export const PATH = {
    shop: '/shop.php',
    warehouseQuery: '/warehouse_query.php',
    logistics: '/logistics.php',
    purchaseProviderQuery: '/purchase_provider_query.php',
    purchaseProviderCreate: '/purchase_provider_create.php',
    goodsPush: '/goods_push.php',
    goodsQuery: '/goods_query.php',
    apiGoodsspecPush: '/api_goodsspec_push.php',
    vipApiGoodsQuery: '/vip_api_goods_query.php',
    suitesQuery: '/suites_query.php',
    goodsClassQuery: '/goods_class_query.php',
    tradePush: '/trade_push.php',
    tradeQuery: '/trade_query.php',
    stockoutOrderQueryTrade: '/stockout_order_query_trade.php',
    logisticsSyncQuery: '/logistics_sync_query.php',
    logisticsSyncAck: '/logistics_sync_ack.php',
    apiGoodsStockChangeQuery: '/api_goods_stock_change_query.php',
    apiGoodsStockChangeAck: '/api_goods_stock_change_ack.php',
    vipStatSalesBySpecShopWarehouseQuery: '/vip_stat_sales_by_spec_shop_warehouse_query.php',
    vipStockoutSalesWeightPush: '/vip_stockout_sales_weight_push.php',
    vipTradeModify: '/vip_trade_modify.php',
    vipApiTradeQuery: '/vip_api_trade_query.php',
    vipInvoiceInfoQuery: '/vip_invoice_info_query.php',
    vipInvoiceInfoUpdate: '/vip_invoice_info_update.php',
    salesRefundPush: '/sales_refund_push.php',
    stockinRefundPush: '/stockin_refund_push.php',
    refundQuery: '/refund_query.php',
    stockinOrderQueryRefund: '/stockin_order_query_refund.php',
    vipStatRefundBySpecShopWarehouseQuery: '/vip_stat_refund_by_spec_shop_warehouse_query.php',
    vipApiRefundQuery: '/api_refund_query.php',
    purchaseOrderPush: '/purchase_order_push.php',
    stockinPurchasePush: '/stockin_purchase_push.php',
    purchaseOrderQuery: '/purchase_order_query.php',
    stockinOrderQueryPurchase: '/stockin_order_query_purchase.php',
    purchaseReturnPush: '/purchase_return_push.php',
    purchaseReturnOrderPush: '/purchase_return_order_push.php',
    purchaseReturnQuery: '/purchase_return_query.php',
    stockoutOrderQueryReturn: '/stockout_order_query_return.php',
    purchaseApplyQuery: '/purchase_apply_query.php',
    stockQuery: '/stock_query.php',
    stockSyncByPd: '/stock_sync_by_pd.php',
    stockPdOrderQuery: '/stock_pd_order_query.php',
    stockinOrderPush: '/stockin_order_push.php',
    stockinOrderQuery: '/stockin_order_query.php',
    stockoutOrderPush: '/stockout_order_push.php',
    stockoutOrderQuery: '/stockout_order_query.php',
    stockTransferPush: '/stock_transfer_push.php',
    stockoutTransferPush: '/stockout_transfer_push.php',
    stockinTransferPush: '/stockin_transfer_push.php',
    stockTransferQuery: '/stock_transfer_query.php',
    vipStockQueryAll: '/vip_stock_query_all.php',
    vipWmsStockinoutOrderPush: '/vip_wms_stockinout_order_push.php',
    vipStockOutsideWmsQuery: '/vip_stock_outside_wms_query.php',
    vipJitReturnStockinOrderQuery: '/vip_jit_return_stockin_order_query.php',
    vipJitStockoutOrderQuery: '/vip_jit_stockout_order_query.php',
};

export const QIMEN_METHOD = {
    shop: 'wdt.shop.query',
    warehouseQuery: 'wdt.warehouse.query',
    logistics: 'wdt.logistics.query',
    purchaseProviderQuery: 'wdt.purchase.provider.query',
    purchaseProviderCreate: 'wdt.purchase.provider.create',
    goodsPush: 'wdt.goods.push',
    goodsQuery: 'wdt.goods.query',
    apiGoodsspecPush: 'wdt.api.goodsspec.push',
    vipApiGoodsQuery: 'wdt.vip.api.goods.query',
    suitesQuery: 'wdt.suites.query',
    goodsClassQuery: 'wdt.goods.class.query',
    tradePush: 'wdt.trade.push',
    tradeQuery: 'wdt.trade.query',
    stockoutOrderQueryTrade: 'wdt.stockout.order.query.trade',
    logisticsSyncQuery: 'wdt.logistics.sync.query',
    logisticsSyncAck: 'wdt.logistics.sync.ack',
    apiGoodsStockChangeQuery: 'wdt.api.goods.stock.change.query',
    apiGoodsStockChangeAck: 'wdt.api.goods.stock.change.ack',
    vipStatSalesBySpecShopWarehouseQuery: 'wdt.vip.stat.sales.by.spec.shop.warehouse.query',
    vipStockoutSalesWeightPush: 'wdt.vip.stockout.sales.weight.push',
    vipTradeModify: 'wdt.vip.trade.modify',
    vipApiTradeQuery: 'wdt.vip.api.trade.query',
    vipInvoiceInfoQuery: 'wdt.vip.invoice.info.query',
    vipInvoiceInfoUpdate: 'wdt.vip.invoice.info.update',
    salesRefundPush: 'wdt.sales.refund.push',
    stockinRefundPush: 'wdt.stockin.refund.push',
    refundQuery: 'wdt.refund.query',
    stockinOrderQueryRefund: 'wdt.stockin.order.query.refund',
    vipStatRefundBySpecShopWarehouseQuery: 'wdt.vip.stat.refund.by.spec.shop.warehouse.query',
    vipApiRefundQuery: 'wdt.api.refund.query',
    purchaseOrderPush: 'wdt.purchase.order.push',
    stockinPurchasePush: 'wdt.stockin.purchase.push',
    purchaseOrderQuery: 'wdt.purchase.order.query',
    stockinOrderQueryPurchase: 'wdt.stockin.order.query.purchase',
    purchaseReturnPush: 'wdt.purchase.return.push',
    purchaseReturnOrderPush: 'wdt.purchase.return.order.push',
    purchaseReturnQuery: 'wdt.purchase.return.query',
    stockoutOrderQueryReturn: 'wdt.stockout.order.query.return',
    purchaseApplyQuery: 'wdt.purchase.apply.query',
    stockQuery: 'wdt.stock.query',
    stockSyncByPd: 'wdt.stock.sync.by.pd',
    stockPdOrderQuery: 'wdt.stock.pd.order.query',
    stockinOrderPush: 'wdt.stockin.order.push',
    stockinOrderQuery: 'wdt.stockin.order.query',
    stockoutOrderPush: 'wdt.stockout.order.push',
    stockoutOrderQuery: 'wdt.stockout.order.query',
    stockTransferPush: 'wdt.stock.transfer.push',
    stockoutTransferPush: 'wdt.stockout.transfer.push',
    stockinTransferPush: 'wdt.stockin.transfer.push',
    stockTransferQuery: 'wdt.stock.transfer.query',
    vipStockQueryAll: 'wdt.vip.stock.query.all',
    vipWmsStockinoutOrderPush: 'wdt.vip.wms.stockinout.order.push',
    vipStockOutsideWmsQuery: 'wdt.vip.stock.outside.wms.query',
    vipJitReturnStockinOrderQuery: 'wdt.vip.jit.return.stockin.order.query',
    vipJitStockoutOrderQuery: 'wdt.vip.jit.stockout.order.query',
};
